name: tutorial
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - python.app
  - pip
  - pip:
    - mlflow>=1.0
    - cloudpickle=0.6.1
    - numpy==1.14.3
    - matplotlib==3.0.2
    - pandas==0.22.0
    - scikit-learn==0.19.1
